# Generated by Django 4.1.11 on 2023-10-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_field',
            field=models.DateField(null=True),
        ),
    ]
